👷 ci: add skaffold build ci action
dynatrace-oss/unguard pull request #41
Opened 2023-03-16 08:23 UTC by W3D3

This PR adds two new GitHub actions:
* One action that is run on every PR that simply builds all the images as a very weak form of catching errors that break the whole application
* One action that is run on pushing to a release branch, that builds and pushes the images to GHCR
    * Images are tagged with `{version}` based on the branch name `release/{version}`.

2023-03-27 07:01 UTC, ammerzon requested changes
Thank you for adding these workflows so we finally have time images on GHCR 😁

2023-03-27 07:27 UTC, W3D3 commented on .github/workflows/release.yaml
> +        uses: hiberbee/github-action-skaffold@latest
Very good point, I think we will need to upgrade it soon enough due to https://github.com/hiberbee/github-action-skaffold/issues/19, but it's probably still a good idea to pin the version.

2023-03-27 09:18 UTC, ammerzon approved these changes
Approved. One general question regarding the commits. Do we have a convention on whether the commit message after the component type should start with an upper case or lower case letter?

![CleanShot 2023-03-27 at 11 16 43](https://user-images.githubusercontent.com/7319168/227898386-ec9decd6-f927-4b29-a042-904c6b6c12cb.png)

2023-03-27 20:12 UTC, W3D3 commented
> Approved. One general question regarding the commits. Do we have a convention on whether the commit message after the component type should start with an upper case or lower case letter?
> 
> ![CleanShot 2023-03-27 at 11 16 43](https://user-images.githubusercontent.com/7319168/227898386-ec9decd6-f927-4b29-a042-904c6b6c12cb.png)

The commitlint action currently doesn't check, but I don't have any strong feelings on how it should be.

2023-03-27 20:13 UTC, merged

2023-03-28 09:21 UTC, ammerzon commented
Same. We could use the format with the uppercase letter because most of the older commits are written this way.

![CleanShot 2023-03-28 at 11 20 54](https://user-images.githubusercontent.com/7319168/228190856-1b5ddcb7-273d-4382-a3a2-4270e186c324.png)

2023-03-28 13:35 UTC, W3D3 commented
> Same. We could use the format with the uppercase letter because most of the older commits are written this way.

We'll just have to extend the [commitlint.config.js](https://github.com/dynatrace-oss/unguard/blob/main/commitlint.config.js) with a rule that forces sentence case for the body then.
See: https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md#body-case