Remove the "v." prefix from the image tags in release action
dynatrace-oss/unguard pull request #45
Opened 2023-05-08 12:50 UTC by MfCrizz

Edited release.yaml to remove the leading 'v.' in the image tag.

2023-05-08 13:42 UTC, W3D3 requested changes

2023-05-08 13:42 UTC, W3D3 commented on .github/workflows/release.yaml
> +          echo TAG_WITH_PREFIX=${{ steps.release-version.outputs.group1 }}
Couldn't we just change the regex for getting the version to include the v, so the group would always just match the version?
Like 
```
      - name: Get release version
        if: startsWith(github.ref_name, 'release')
        uses: actions-ecosystem/action-regex-match@v2
        id: release-version
        with:
          text: ${{ github.ref_name }}
          regex: '^release\/v(.*)$'
```

2023-05-08 13:43 UTC, W3D3 commented
Pls change the PR name to be the commit message, as it takes the PR name as the commit message when merging with squash.

2023-05-12 05:50 UTC, MfCrizz commented on .github/workflows/release.yaml
> +          echo TAG_WITH_PREFIX=${{ steps.release-version.outputs.group1 }}
Yes, that's a more elegant way.

2023-05-12 07:22 UTC, merged