:star2: [WIP] Transition Unguard to Helm
dynatrace-oss/unguard pull request #47
Opened 2023-05-24 11:32 UTC by MfCrizz

🚀 This PR transitions **Unguard** to a **Helm Chart**. 🚀
Please have a look and try it yourself. Feedback is very appreciated! :smile: 

To get started please follow  `/docs/DEPLOYMENT.md`

Note: The individual commits will be squashed before merging.

2023-05-24 12:12 UTC, W3D3 requested changes

2023-05-24 12:12 UTC, W3D3 commented on docs/DEV-GUIDE.md
> +      * Optional add NGINX-Ingress
[ISSUE] Be more specific here
```suggestion
      * Optionally add an nginx ingress controller if you want to expose Unguard locally without port-forwarding
```

2023-05-24 12:12 UTC, W3D3 commented on docs/DEV-GUIDE.md
> +    > **Note**: If you deploy with **minikube** don't forget to forward the Docker daemon first (see above)
skaffold pretty reliably detects a running minikube and should adapt automatically, so not sure if we should repeat this here. Maybe even put the whole paragraph above into a troubleshooting section at the bottom.
Seee https://skaffold.dev/docs/environment/local-cluster/#auto-detection

2023-05-24 12:12 UTC, W3D3 commented on docs/DEV-GUIDE.md
> +Often, you might also want to also deploy **Jaeger**. [See these instructions](TRACING.md)
[CLARIFY] This looks misleading, the `tracing` profile would not install Jaeger? Maybe rephrase this?
```suggestion
To enable distributed tracing, install a tracing collector like **Jaeger** and use the `tracing` profile. [See these instructions.](TRACING.md)
```
Also, shouldn't we link here to docs/JAEGER-TRACING-DEPLOYMENT.md?

2023-05-24 12:12 UTC, W3D3 commented on skaffold.yaml
> +    - image: unguard-proxy-service
[CLARIFY] Why the reordering?

2023-05-24 12:38 UTC, MfCrizz commented on skaffold.yaml
> +    - image: unguard-proxy-service
It happened during the implementation but there is no reason.
Will be undone.

2023-05-24 13:25 UTC, MfCrizz commented on chart/README.md
> +> **Note**: This chart presumes an already running and configured MariaDB database in the cluster
Good point!

2023-05-24 13:50 UTC, MfCrizz commented on docs/DEV-GUIDE.md
> +Often, you might also want to also deploy **Jaeger**. [See these instructions](TRACING.md)
Yes. TRACING.md also needs to be deleted/reworked

2023-05-25 13:34 UTC, MfCrizz commented on README.md
>  ## 🖥️ Local Deployment
Great idea :D

2023-05-31 10:08 UTC, MfCrizz commented on chart/values.yaml
> +        JAEGER_AGENT_HOST: agent # change depending on your jaeger deployment
The name is derived from the name of the mariaDB installation. Yes, this would be a good idea.

2023-06-05 10:45 UTC, W3D3 requested changes

2023-06-09 17:27 UTC, MfCrizz commented on chart/templates/_helpers.tpl
> +{{- end }}
Yes, I also removed most of the auto generated methods.

2023-06-09 20:01 UTC, MfCrizz commented on .github/workflows/release.yaml
> +          find: "tag: (.)*"
We need to change the default value of the image tags to their corresponding values for this build. This can be only done in the values.yaml. 
But we can replace the regex with a more safer variant " \btag:.*" -> This matches only if the value starts with "tag:...."
The other two replace action should be safe as there are no other values with the same name allowed. But here we can also replace the regex with a safer version.

2023-06-13 06:50 UTC, MfCrizz commented on skaffold.yaml
>        context: src/status-service
As discussed, can be don in a later step :)

2023-06-13 06:50 UTC, MfCrizz commented on chart/README.md
> +| `aws.enabled`                    | Enable for AWS cluster deployment               | `false`           |
Section is now reworked

2023-06-19 14:25 UTC, MfCrizz commented on .github/workflows/release.yaml
> +          find: "tag: (.)*"
Is now replaced with `yaml-update-action` . But sadly a wildcard wasn't working, so now all image tags are explicitly listed.

2023-06-23 11:01 UTC, W3D3 approved these changes
LGTM! :smile:

2023-06-29 15:47 UTC, lepidopterane-atsmith commented
hi! Sarah Abowitz (she/her) here. I've been running into some issues installing this version of unguard with helm and minikube. everything's been done in the same directory I keep this code on my ubuntu VM. Things I have done:

1. start minikube cluster with `minikube start --addons=ingress --profile unguard` (`kubectl get nodes` works after this)
2. adding the bitnami repo and unguard-mariadb each proceed without error.
3. installing unguard via helm results in the following:
```
$ helm install unguard  oci://ghcr.io/dynatrace-oss/unguard/chart/unguard --wait --namespace unguard --create-namespace
Pulled: ghcr.io/dynatrace-oss/unguard/chart/unguard:0.8.0
Digest: sha256:8426e1108a691cd611b214d02f2f61ba44085882d9111b107b69f39afb38c41f
Error: INSTALLATION FAILED: context deadline exceeded
```
It was suggested I run the following for diagnostic purposes, so here's how that went:
```
$ minikube --profile unguard ssh docker pull ghcr.io/dynatrace-oss/unguard/chart/unguard:0.8.0
0.8.0: Pulling from dynatrace-oss/unguard/chart/unguard
unsupported media type application/vnd.cncf.helm.config.v1+json
ssh: Process exited with status 1
```
willing to answer any questions / meet with people / help how I can wrt this.

2023-06-29 16:49 UTC, MfCrizz commented
Hi Sarah, 
which version of Helm do you have installed?
Could you please try to install the chart adding the `--debug` flag?
`helm install unguard  oci://ghcr.io/dynatrace-oss/unguard/chart/unguard --wait --namespace unguard --create-namespace --debug`
Does the installation using the local chart work?
`helm install unguard ./chart --wait --namespace unguard --create-namespace`

2023-06-30 10:17 UTC, merged