🧑‍💻 feat(helm): Add default AWS LB annotations
dynatrace-oss/unguard pull request #62
Opened 2023-10-11 06:58 UTC by MfCrizz

Adds default AWS Load Balancer annotations. Now only the `aws.enabled` value needs to be enabled and the ingress will be configured with save default annotations.

2023-11-15 13:45 UTC, W3D3 requested changes

2023-11-15 18:27 UTC, blu3r4y commented
Shouldn't the docs also mention that one needs to install the AWS Load Balancer Controller. Novices might be confused why nothing will happen otherwise. I don't mean to explain everything step-by-step, but putting a link to the documentation wouldn't hurt: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/

2023-11-17 12:45 UTC, W3D3 commented on chart/README.md
> +This steps assume that an AWS Load Balancer Controller is installed. See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/ for more information.
[NIT] These

2023-11-17 12:48 UTC, W3D3 approved these changes

2023-11-17 13:00 UTC, MfCrizz commented on chart/README.md
> +This steps assume that an AWS Load Balancer Controller is installed. See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/ for more information.
Done

2023-11-17 13:38 UTC, merged