🏗️ Feature/Reduce container image sizes
dynatrace-oss/unguard pull request #77
Opened 2024-06-03 11:41 UTC by orazefabian

## Description

This PR reduces the container images sizes and aims to fix #21 by:

1. Changing the base images wherever it is possible to `-alpine` or `-slim`
2. Adding/improving `.gitignore` files
3. Rewriting the `user-simulator` service to drop flood and use [puppeteer](https://pptr.dev/) instead to generate user activity. 

To sum up, the proposed changes reduce the size of all images combined from `~7.6 GB` to `~4.12 GB`

2024-06-05 08:23 UTC, W3D3 requested changes

2024-06-05 08:23 UTC, W3D3 commented on README.md
> +| [user-simulator](./src/user-simulator)                     | Node.js         | default         | Creates synthetic user traffic by simulating an Unguard user using a real browser. Acts as a load ge
[NIT] Could say `Node.js (Puppeteer)`

2024-06-05 08:23 UTC, W3D3 commented on src/profile-service/Dockerfile
> +# RUN apt-get update && apt-get install markdown -y
[Q] Can we really remove this? I think we need this package.

2024-06-05 08:23 UTC, W3D3 commented on src/user-simulator/Dockerfile
> +#ENV FRONTEND_ADDR="unguard.kube/ui"
[ISSUE] Remove commented out code

2024-06-05 08:23 UTC, W3D3 commented on src/user-simulator/Dockerfile
> +RUN npm install -g tsc
[DISCUSS] Can we add this to the (dev)dependencies if we need it to build it?

2024-06-05 08:23 UTC, W3D3 commented on src/user-simulator/default-user-sim.perf.ts
> +import {BioList, ImageUrlPosts, TextPosts, UrlPosts} from "./types";
[Q] Did we run `prettier` on this file?

2024-06-05 12:35 UTC, orazefabian commented on src/user-simulator/Dockerfile
> +RUN npm install -g tsc
Yes, can and will do that

2024-06-05 12:41 UTC, orazefabian commented on src/profile-service/Dockerfile
> +# RUN apt-get update && apt-get install markdown -y
You are right, we need this

2024-06-07 06:28 UTC, W3D3 approved these changes
Tried it out locally and everything still works as expected! LGTM!

2024-06-07 08:20 UTC, merged