✨ feat(payment-service): Adds new payment service written in Python
dynatrace-oss/unguard pull request #80
Opened 2024-07-16 07:59 UTC by orazefabian

## Description

This PR adds a payment service to Unguard. 
The service is written in `Python 3.8.0` using `Flask` for the REST API and `poetry` for dependency management. 

### Changes:
* Adds a new page to the frontend where a user can enter a credit card
* Adds the python service 
* Updates configuration files for skaffold and helm
* Adds tracing with opentelementry for new service
* Updates `user-simulator` to act upon new payment service page
* Updates documentation

## Screenshot

![payment-service](https://github.com/user-attachments/assets/281599d2-6e67-4e7b-b263-f568484da595)

2024-07-17 10:09 UTC, AlejandroCamba commented on src/frontend/site.js
> +            res.redirect('back');
If we refresh the page this wouldn't work anymore, maybe it doesn't matter in unguard though :smile:

2024-07-17 10:09 UTC, AlejandroCamba commented on src/payment-service/README.md
> +2) Install [poetry](https://python-poetry.org/docs/) for dependency management and packaging
should we also be more specific here about installing a specific version? and also maybe saying how to do it, otherwise the local and the docker running versions will be different

2024-07-17 11:20 UTC, W3D3 commented on docs/TRACING.md
> +    kubectl port-forward -n unguard service/jaeger-query 16686:80
This was a mistake, the port is 16686 on the container itself, but as this port forwards the service (which already mapped the port to 80), this is the correct command.

2024-07-17 11:22 UTC, W3D3 commented on src/frontend/site.js
> +            username: getJwtUser(req.cookies),
These can be two different things. `username` is the username of the profile you're looking at and `getJwtUser` will give you the currently logged in user's username.

2024-07-17 11:25 UTC, W3D3 commented on src/frontend/site.js
> +            paymentInformation: paymentInformation,
I think we use `username`, `profileName`, `membership`, and some `baseData` stuff but we could cut `isAdManager`?

2024-07-17 11:26 UTC, W3D3 commented on src/frontend/site.js
> +            res.redirect('back');
WDYM it won't work anymore? This is just supposed to bring you back to the payment info page.

2024-07-17 11:27 UTC, W3D3 commented on src/frontend/views/payment.njk
> +        // Example starter JavaScript for disabling form submissions if there are invalid fields
[NIT] I guess this comment could be removed

2024-07-17 11:30 UTC, W3D3 commented on src/payment-service/README.md
> +A web service where a user can enter a credit card as payment information.
Kind of misleading, it is a restful service where one can do create/read a credit card that is associated to a user. No real "entering" can happen as this doesn't include a UI.

2024-07-17 11:33 UTC, AlejandroCamba commented on src/frontend/site.js
> +            res.redirect('back');
The browser loses what page you visited last if you refresh the page in the payment screen, but like i said it might be too nitty for unguard :smile:

2024-07-17 11:33 UTC, W3D3 commented on src/user-simulator/default-user-sim.perf.ts
> +    await addCreditCardInformation(page, config, user)
[NIT] Mixing tabs and spaces :sweat:

2024-07-17 11:34 UTC, W3D3 requested changes
A few small things need to be fixed still, but looks good overall.

2024-07-17 11:35 UTC, W3D3 commented on src/payment-service/README.md
> +2) Install [poetry](https://python-poetry.org/docs/) for dependency management and packaging
Poetry will absolutely complain and not let you install it with anything but Python 3.8.0, but I would also prefer a small segment about how to easily install it.

2024-07-17 11:38 UTC, W3D3 commented on src/frontend/site.js
> +            res.redirect('back');
But the payment screen then still is the last screen you visited when refreshing? :thinking: 
This is just so that you go from `GET /payment-info/` to `POST /payment-info` (by submitting the form) and back to `GET /payment-info`. You can refresh the `GET /payment-info` page as often as you like tbh, will not change a thing.

2024-07-17 11:38 UTC, AlejandroCamba commented on src/frontend/site.js
> +            username: getJwtUser(req.cookies),
But you will always see the payment info of the currently logged in user, or when would that not be the case? :thinking: well in unguard you never know :smile:

2024-07-17 11:39 UTC, W3D3 commented
Another tiny NIT, your commit message should use sparkles (✨) instead of the wrench to indicate a new feature:
https://gist.github.com/parmentf/035de27d6ed1dce0b36a

2024-07-18 07:52 UTC, orazefabian commented on src/payment-service/README.md
> +1) Have Python 3.8.0 installed
Will do 👍🏼

2024-07-18 09:01 UTC, orazefabian commented on src/payment-service/README.md
> +6) Run `poetry run python payment_service/run.py` to start the flask server
This doesn't make sense, `sqlite3` should be a standard library in python since 2.5 or so

2024-07-18 09:21 UTC, orazefabian commented on src/payment-service/README.md
> +6) Run `poetry run python payment_service/run.py` to start the flask server
Found the issue, you need to have `libsqlite3-dev` installed on your machine 
Will add that to the README 👍🏼

2024-07-18 11:00 UTC, orazefabian commented on src/frontend/site.js
> +            paymentInformation: paymentInformation,
Yes we need all but `isAdManager`

2024-07-18 11:16 UTC, orazefabian commented on src/user-simulator/default-user-sim.perf.ts
> +    await addCreditCardInformation(page, config, user)
Will make it consistent

2024-07-18 11:25 UTC, orazefabian commented on src/frontend/site.js
> +            username: getJwtUser(req.cookies),
I suppose this is the intended way, will not change it for now.

2024-07-18 14:27 UTC, W3D3 commented on src/payment-service/README.md
> +   1) You need to have `libsqlite3-dev` installed e.g. on Ubuntu with `sudo apt install libsqlite3-dev`
I think you only need it when installing Python 3.8.0 via `pyenv` though, so would be nice if that would be clear here. Maybe move this below "Install pyenv"?

2024-07-18 14:30 UTC, W3D3 commented on src/payment-service/Dockerfile
> +RUN curl -sSL https://install.python-poetry.org | python -
[NIT] Would prefer not to install curl and run a script with python here tbh.
Could this also work with just `pip`, i.e. `RUN pip install poetry==1.8.3`?

2024-07-18 14:34 UTC, W3D3 commented on docs/images/unguard-architecture.svg
Could we also denote the build in SQLite DB the same way we did it for the build in H2 db of the profile service? So that it will not cause confusion as if this DB is accessible from other services.

2024-07-18 14:37 UTC, W3D3 commented on chart/values.yaml
> +        OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
Does this make sense to enable by default if we set `OTEL_LOGS_EXPORTER` to none?

2024-07-18 14:41 UTC, W3D3 commented on chart/templates/payment-service.yaml
> +          env:
[NIT] I honestly think it would be nicer if we resolved all env vars here dynamically and not restrict it to this set, as it is kind of error prone to put it in the `values.yaml` but forget it here, but not sure how hard that is to do in helm templating language. Keeping this is fine as well.

2024-07-18 14:41 UTC, W3D3 commented on README.md
> +| [payment-service](./src/payment-service)                   | Python Flask        | default         | Service REST API for adding or retrieving payment information in form of credit cards.
```suggestion
| [payment-service](./src/payment-service)                   | Python Flask        | default         | Serves REST API for adding and retrieving credit card payment information associated with a user.                                                      |
```

2024-07-18 14:42 UTC, W3D3 commented on README.md
> +| [payment-service](./src/payment-service)                   | Python Flask        | default         | Service REST API for adding or retrieving payment information in form of credit cards.
Table formatting might be off, I suggest not just committing the suggestion ;)

2024-07-19 06:11 UTC, orazefabian commented on src/payment-service/README.md
> +   1) You need to have `libsqlite3-dev` installed e.g. on Ubuntu with `sudo apt install libsqlite3-dev`
yes that is right, I will move it below "Install pyenv"

2024-07-19 06:22 UTC, orazefabian commented on src/payment-service/Dockerfile
> +RUN curl -sSL https://install.python-poetry.org | python -
I can change that, should also work using `pip install`

2024-07-19 06:25 UTC, orazefabian commented on chart/values.yaml
> +        OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
Good point, probably does not make much sense. Will set the default `OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED` to false, and override that to true in the `chart/tracing.yaml`

2024-07-19 06:36 UTC, orazefabian commented on docs/images/unguard-architecture.svg
Ok, so make the SQLite DB rectangle be within the payment-service, like the H2 is within the profile service?

2024-07-19 07:11 UTC, orazefabian commented on chart/templates/payment-service.yaml
> +          env:
Yes totally agree, ideally all service configuration files should be improved. However, I believe this should tackled in another PR

2024-07-19 08:11 UTC, W3D3 commented on src/payment-service/Dockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommends \
Why do we still need this? I thought this was needed to install poetry with the curl command, do we also need it if we install it with pip?

2024-07-19 08:33 UTC, orazefabian commented on src/payment-service/Dockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommends \
Good catch, I don't think we need this any longer with pip. Will try it out and remove them if it works without 👍🏼

2024-07-22 07:35 UTC, W3D3 approved these changes

2024-07-22 08:29 UTC, merged